// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "78990acddbb865c6cd4fa3ee1d83805b"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"d226a57aea22e13f3a7ebe7ab9286457": "1f8b08000000000000ffdc56c16edb300cbdfb2b04b6a721adb7d3009f771cb0023b16392831eda8b52555a2871581ff7db0133bb24d255bd05d72a5c947bda7475afb4408b8f7db1dd61232013b229ba5e98b37fae1107d34ae4c73270b7af8fc353dc4ee60d5d5e55828ad4819ed21131d9410a0b42759553f09ed181402e8dd62d7c06c5e704b7d7d1fb7ce5874a4d007d942c05ba55e3d6adf15ede1de61d155dfa541cff494d31e0bdb11d7e15ba31ce69089670ef5185b8f0532cf7b58593d85472a64e53109b0a1b1a59339de2e41a57f99d71be6d7e89bf7a827b4dfd06f9db25d3e47d29353ba3c91ac95fe8ebaa41d64e2cb04cc34641bf21c88744ebe9f3014613dd328a2695c552140cb1a67b1e5c1838fed2aacee76d793ec795c89e0b0c4dfd797db7f6d9e303867ef3a48633d34683806d64185d1f8a398a5efa7408188623d65b7c83c887531cd0e60a7332521fdc16c9399ba7630190345f50f35cfd991e93ff1d33d9f33fe265dd9d4a869e1737e8a043f496749c44cb475b19e4729d9aaa29265f4b08b418e7b953ffc33e8a6aa60051b632a941a56a09b7a830e5603aff54562cb9d74e69686e4648ed9fed566bdb0af7bb3454c346cf064e8da77e4b4e4bc3cbca5aedbbcbc16e1af8f1dc0e3f3e6237b862f26bea7fe0f4ca7bff969dff126ac2442a719dbc2e3a78fd57d7c54458e72f6e7de267f020000ffff898c6019aa0b0000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("schema", "./schema")
		b.SetResolver("qliksense.json", packr.Pointer{ForwardBox: gk, ForwardPath: "d226a57aea22e13f3a7ebe7ab9286457"})
		}()

	return nil
}()
